### ISSUE TITLE
Add initial bank of topics from published lit

### ISSUE THREAD

**Issue by JamesPHoughton** [Watts-Lab/deliberation-topics#7]
As an experimenter, I want to find an existing bank of discussion topics for participants to engage in that is validated through use, easily justifiable ("why did you use those particular topics?"), and that I can clearly map to a relevant dimension in the space I wish to explore. This will allow me to conduct the initial round of deliberation exercises without having to spend excess effort building, validating, and measuring my own pool of deliberation questions.

[Baldassari and Gelman](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4056259/) and later [Kozlowski and Murphy](https://www.sciencedirect.com/science/article/abs/pii/S0049089X2030096X) identify a bank of ~47 questions from the ANES which may make a good initial bank of discussion topics. They also define a measure of partisan alignment of issues that we can use as one of our context axes. We should 

- [x] format these as discussion topics (boring, but not excessively time consuming), all in a single folder in `/topics/ANES` with a single readme.
- [x] replicate the partisan alignment analysis with updated data from the latest ANES, save the analysis in `/data` and document the particular measure and analysis process.
- [ ] #9

**Comment by isaacgat** [comment]
. I'm choosing just the x variable to be used for our correlations because it's a summary variable from 1-7 or 1-4
. We will make the topics a "should" question because it makes more sense to pose this instead of anchoring our group with a declarative statement.

**Comment by JamesPHoughton** [comment]
Can you list here an example of one of the questions and subquestions, just to give context to what it means to choose the `x` variable? A screenshot would suffice. Also would love to know what the original papers did!

**Comment by isaacgat** [comment]
So here's how a lot of these questions break down: with each issue, the first question asks a yes/no/maybe, the second asks for the strength of that prior opinion, and the third "summarizes" these two by asking participants to place themselves along a Likert scale in terms of agreement/disagreement and strength of said agreement. I plan on finding the correlation between party and the "x" variables because they seem to tell us the most about a participant's opinion and because they are already coded to run 1-7 (sometimes 1-5) in order of strength whereas the first two questions have responses that are not so neatly mappable. The papers we were looking at were analyzing data by year and I don't know exactly how the responses were coded for the every-year data set; I will look into it and comment my findings.


![Image](https://user-images.githubusercontent.com/103131500/171435080-ecd78334-a6ef-4ebe-bc76-b99eaa784db6.png)



![Image](https://user-images.githubusercontent.com/103131500/171435102-89b94f67-a077-477e-8578-f500f83712c5.png)



![Image](https://user-images.githubusercontent.com/103131500/171435118-53e90acd-5111-4f75-b89c-d205f1656fcb.png)

**Comment by isaacgat** [comment]
After checking the variables used in the Kozlowski paper and the replication script of the Baldassari paper-they use a mix of 2, 5, and 7-point scales. They are using the exact same summary questions that I am (except the wording is different and they've added some new questions and deleted some other ones in the 2020 data), ignoring the favor/oppose and strength of opinion questions. Looks like we're on the right track.

**Comment by isaacgat** [comment]
Work is done for this week's topic. I'm going to turn the last task on this issue into a new issue for next week.
